services:
  - type: static_site
    name: sei-com-ai-frontend
    staticPublishPath: ./dist
    buildCommand: npm ci && npm run prebuild && npm run build:render
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /index.html
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://sei-jxdn.onrender.com/api/v1
      - key: REACT_APP_ENV
        value: production
      - key: NODE_VERSION
        value: "18.20.4"
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
      - key: CI
        value: "false" 