services:
  - type: static_site
    name: sei-com-ai-frontend
    staticPublishPath: ./dist
    buildCommand: npm run build:render
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://sei-jxdn.onrender.com/api/v1
      - key: REACT_APP_ENV
        value: production
      - key: NODE_VERSION
        value: "18" 